version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  my-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      MONGO_HOST: mongo
    depends_on:
      - mongo